# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\create_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateClass(object):
    def setupUi(self, CreateClass):
        CreateClass.setObjectName("CreateClass")
        CreateClass.resize(304, 140)
        self.gridLayoutWidget = QtWidgets.QWidget(CreateClass)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.NameValue = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.NameValue.setObjectName("NameValue")
        self.gridLayout.addWidget(self.NameValue, 2, 1, 1, 1)
        self.PathValue = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.PathValue.setObjectName("PathValue")
        self.gridLayout.addWidget(self.PathValue, 1, 1, 1, 1)
        self.Path = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Path.setBaseSize(QtCore.QSize(10, 0))
        self.Path.setObjectName("Path")
        self.gridLayout.addWidget(self.Path, 1, 0, 1, 1)
        self.Name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Name.setObjectName("Name")
        self.gridLayout.addWidget(self.Name, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(CreateClass)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(CreateClass)
        QtCore.QMetaObject.connectSlotsByName(CreateClass)

    def retranslateUi(self, CreateClass):
        _translate = QtCore.QCoreApplication.translate
        CreateClass.setWindowTitle(_translate("CreateClass", "Form"))
        self.Path.setText(_translate("CreateClass", "Path"))
        self.Name.setText(_translate("CreateClass", "Name"))
        self.pushButton.setText(_translate("CreateClass", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateClass = QtWidgets.QWidget()
    ui = Ui_CreateClass()
    ui.setupUi(CreateClass)
    CreateClass.show()
    sys.exit(app.exec_())
