# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 475)
        self.Body = QtWidgets.QWidget(MainWindow)
        self.Body.setObjectName("Body")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Body)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 971, 621))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.Body)
        self.MenuBar = QtWidgets.QMenuBar(MainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 841, 22))
        self.MenuBar.setObjectName("MenuBar")
        self.menuFile = QtWidgets.QMenu(self.MenuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.MenuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.MenuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.MenuBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionClass = QtWidgets.QAction(MainWindow)
        self.actionClass.setObjectName("actionClass")
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuEdit.addAction(self.actionClass)
        self.menuAbout.addAction(self.actionInfo)
        self.MenuBar.addAction(self.menuFile.menuAction())
        self.MenuBar.addAction(self.menuEdit.menuAction())
        self.MenuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.actionInfo.triggered.connect(self.Body.repaint) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Generate"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionClass.setText(_translate("MainWindow", "Class"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
